export type GameStatus = 'LIVE' | 'COMING_SOON';

export interface GameCatalogItem {
  id: string;
  name: string;
  developer: string;
  platform: string;
  description: string;
  status: GameStatus;
  icon: string;
  color: string;
  bgGradient: string;
  borderColor: string;
  /** Community games have no official player-stat API — they exist for challenges/community play only. */
  community?: boolean;
}

export const GAMES_CATALOG: GameCatalogItem[] = [
  // ── P0 CANONICAL GAMES ─────────────────────────────────────────────
  {
    id: 'bgmi',
    name: 'BGMI',
    developer: 'Krafton',
    platform: 'Mobile',
    description: 'Custom room ID handoff, squad matchmaking & teammate discovery.',
    status: 'LIVE',
    community: true,
    icon: '📱',
    color: '#EAB308',
    bgGradient: 'from-amber-950/60 via-yellow-950/40 to-black',
    borderColor: 'border-yellow-500/40',
  },
  {
    id: 'clashofclans',
    name: 'Clash of Clans',
    developer: 'Supercell',
    platform: 'Mobile',
    description: 'Sync Town Hall level, Trophies, War Stars, Clan & Hero levels from Supercell API.',
    status: 'LIVE',
    icon: '🏰',
    color: '#EAB308',
    bgGradient: 'from-amber-950/60 via-yellow-950/40 to-black',
    borderColor: 'border-yellow-500/40',
  },
  {
    id: 'pubg_mobile',
    name: 'PUBG Mobile',
    developer: 'Level Infinite',
    platform: 'Mobile',
    description: 'Separate global build from BGMI. Custom room code sharing & squad pairing.',
    status: 'LIVE',
    community: true,
    icon: '🪖',
    color: '#F97316',
    bgGradient: 'from-orange-950/60 via-amber-950/40 to-black',
    borderColor: 'border-orange-500/40',
  },
  {
    id: 'freefire',
    name: 'Free Fire MAX',
    developer: 'Garena',
    platform: 'Mobile',
    description: 'Self-reported UID trust model, BR/CS Squad teammate matching & reputation ratings.',
    status: 'LIVE',
    community: true,
    icon: '🔥',
    color: '#F97316',
    bgGradient: 'from-orange-950/60 via-amber-950/40 to-black',
    borderColor: 'border-orange-500/40',
  },
  {
    id: 'smashkarts',
    name: 'Smash Karts',
    developer: 'Smash Karts',
    platform: 'Web / Mobile Browser',
    description: 'Direct web party room link handoff for instant multiplayer battle kart races.',
    status: 'LIVE',
    community: true,
    icon: '🏎️',
    color: '#38BDF8',
    bgGradient: 'from-sky-950/60 via-slate-950/40 to-black',
    borderColor: 'border-sky-500/40',
  },

  // ── P1 CANONICAL GAMES ─────────────────────────────────────────────
  {
    id: 'codm',
    name: 'Call of Duty: Mobile',
    developer: 'Activision',
    platform: 'Mobile',
    description: 'MP 5v5 & BR private room code sharing and teammate discovery.',
    status: 'LIVE',
    community: true,
    icon: '🎯',
    color: '#10B981',
    bgGradient: 'from-emerald-950/60 via-slate-950/40 to-black',
    borderColor: 'border-emerald-500/40',
  },
  {
    id: 'roblox',
    name: 'Roblox',
    developer: 'Roblox Corporation',
    platform: 'Multi-platform',
    description: 'Private server link handoff & party play joining.',
    status: 'LIVE',
    community: true,
    icon: '🧱',
    color: '#EF4444',
    bgGradient: 'from-red-950/60 via-slate-950/40 to-black',
    borderColor: 'border-red-500/40',
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    developer: 'Mojang Studios',
    platform: 'Multi-platform',
    description: 'Server IP:Port & Realm invite code manual handoff.',
    status: 'LIVE',
    community: true,
    icon: '⛏️',
    color: '#22C55E',
    bgGradient: 'from-green-950/60 via-slate-950/40 to-black',
    borderColor: 'border-green-500/40',
  },
  {
    id: 'ludoking',
    name: 'Ludo King',
    developer: 'Gametion',
    platform: 'Mobile',
    description: '8-digit Private Room Code sharing for 2P/4P Ludo matches.',
    status: 'LIVE',
    community: true,
    icon: '🎲',
    color: '#EAB308',
    bgGradient: 'from-yellow-950/60 via-slate-950/40 to-black',
    borderColor: 'border-yellow-500/40',
  },
  {
    id: 'eightballpool',
    name: '8 Ball Pool',
    developer: 'Miniclip',
    platform: 'Mobile / Web',
    description: 'Unique ID friend search & 1v1 match challenge handoff.',
    status: 'LIVE',
    community: true,
    icon: '🎱',
    color: '#3B82F6',
    bgGradient: 'from-blue-950/60 via-slate-950/40 to-black',
    borderColor: 'border-blue-500/40',
  },
  {
    id: 'brawlstars',
    name: 'Brawl Stars',
    developer: 'Supercell',
    platform: 'Mobile',
    description: 'Sync trophies, wins & Brawler stats from official Supercell API.',
    status: 'LIVE',
    icon: '⭐',
    color: '#EC4899',
    bgGradient: 'from-pink-950/60 via-slate-950/40 to-black',
    borderColor: 'border-pink-500/40',
  },
  {
    id: 'clashroyale',
    name: 'Clash Royale',
    developer: 'Supercell',
    platform: 'Mobile',
    description: 'Sync trophies, arena, win rate & battle stats from official Supercell API.',
    status: 'LIVE',
    icon: '👑',
    color: '#3B82F6',
    bgGradient: 'from-blue-950/60 via-slate-950/40 to-black',
    borderColor: 'border-blue-500/40',
  },
  {
    id: 'realcricket',
    name: 'Real Cricket',
    developer: 'Nautilus Mobile',
    platform: 'Mobile',
    description: 'Private Room ID sharing for 2 Over / 5 Over multiplayer cricket matches.',
    status: 'LIVE',
    community: true,
    icon: '🏏',
    color: '#8B5CF6',
    bgGradient: 'from-purple-950/60 via-slate-950/40 to-black',
    borderColor: 'border-purple-500/40',
  },
  {
    id: 'efootball',
    name: 'eFootball',
    developer: 'Konami',
    platform: 'Multi-platform',
    description: 'Match Room Number sharing for 1v1 & Co-op 3v3 football matches.',
    status: 'LIVE',
    community: true,
    icon: '⚽',
    color: '#06B6D4',
    bgGradient: 'from-cyan-950/60 via-slate-950/40 to-black',
    borderColor: 'border-cyan-500/40',
  },
  {
    id: 'drdriving',
    name: 'Dr. Driving',
    developer: 'SUD Inc.',
    platform: 'Mobile',
    description: 'Single-player career title. Track high scores (multiplayer joining unsupported).',
    status: 'LIVE',
    community: true,
    icon: '🚗',
    color: '#64748B',
    bgGradient: 'from-slate-900 via-zinc-950 to-black',
    borderColor: 'border-slate-500/40',
  },
];
